Ms dict updates
aflorithmic/apiaudio-python pull request #79
Opened 2022-05-04 14:26 UTC by Sjhunt93

2022-05-04 16:06 UTC, LindaKivine requested changes

2022-05-04 16:06 UTC, LindaKivine commented on README.md
> +    - `useDictionary` (bool) - Applies lexi to the script text.
We are calling it Pronunciation Dictionary now. Lets try to get rid of lexi as much as possible

2022-05-12 09:54 UTC, LindaKivine requested changes
updated lexi to pronunciation dictionary

2022-05-12 09:54 UTC, LindaKivine commented on README.md
> +    - `useDictionary` (bool) - Applies lexi to the script text.
```suggestion
    - `useDictionary` (bool) - Applies pronunciation dictionary to the script text.
```

2022-05-12 09:54 UTC, LindaKivine commented on README.md
> +To use lexi end-to-end ensure that you supply a voice whose language matches that of the language of the dictionary you wish to use, and then supply `useDictionary=true` to the speech create call (se
```suggestion
To use pronunciation dictionary end-to-end ensure that you supply a voice whose language matches that of the language of the dictionary you wish to use, and then supply `useDictionary=true` to the speech create call (see the example below). See the [Voice](#voice) resource to get a list of voices and their corresponding language code, or browse our available voices [here](#https://library.api.audio/voices)
```

2022-05-12 09:54 UTC, LindaKivine commented on README.md
>  Lexi methods are:
```suggestion
Prononciation dictionary methods are:
```

2022-05-12 12:59 UTC, springcoil approved these changes
LGTM

2022-05-13 14:49 UTC, LindaKivine approved these changes

2022-05-17 10:15 UTC, merged